--------------------------------------------------------
--  File created - csütörtök-november-08-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table SNEAK_HIGHSCORES
--------------------------------------------------------

  CREATE TABLE "ADMIN"."SNEAK_HIGHSCORES" 
   (	"MAP_NO" NUMBER(3,0), 
	"BESTSCORE" NUMBER(20,0), 
	"BESTTIME" VARCHAR2(12 BYTE), 
	"BESTNAME" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index MAP_NO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMIN"."MAP_NO_PK" ON "ADMIN"."SNEAK_HIGHSCORES" ("MAP_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table SNEAK_HIGHSCORES
--------------------------------------------------------

  ALTER TABLE "ADMIN"."SNEAK_HIGHSCORES" MODIFY ("MAP_NO" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."SNEAK_HIGHSCORES" ADD CONSTRAINT "MAP_NO_PK" PRIMARY KEY ("MAP_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
