CREATE USER SNAKE IDENTIFIED BY snakePass;

GRANT ALL PRIVILEGES TO SNAKE;

CREATE TABLE SNAKE_HIGHSCORES 
(
  MAP_NO NUMBER(3, 0) NOT NULL 
, BESTSCORE NUMBER(20, 0) 
, BESTTIME VARCHAR2(12 BYTE) 
, BESTNAME VARCHAR2(50 BYTE) 
) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

CREATE UNIQUE INDEX MAP_NO_PK ON SNAKE_HIGHSCORES (MAP_NO ASC) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

ALTER TABLE SNAKE_HIGHSCORES
ADD CONSTRAINT MAP_NO_PK PRIMARY KEY 
(
  MAP_NO 
)
USING INDEX MAP_NO_PK
ENABLE;
